version: "3.8"

services:
  navidrome:
    build: .
    container_name: navidrome
    env_file: .env
    volumes:
      - ./rclone.conf.template:/config/rclone.conf.template:ro
      - navidrome_data:/data
    ports:
      - "4533:4533"
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped

volumes:
  navidrome_data:
